# Deployment Manifest for Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: living-room-air-mki
  namespace: iot-devices
spec:
  selector:
    matchLabels: 
      app: living-room-air-mki
  replicas: 1
  template:
    metadata:
      labels:
        app: living-room-air-mki
    spec:
      nodeName: rpinode2
      containers:
        - name: living-room-air-mki
          image: markhamlee/airquality_plantower_s5003:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  key: MQTT_USER
                  name: mqtt-creds
                  optional: false
            - name: MQTT_SECRET
              valueFrom:
                secretKeyRef:
                  key: MQTT_SECRET
                  name: mqtt-creds
                  optional: false
            - name: MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: MQTT_BROKER
                  name: mqtt-data
                  optional: false
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  key: MQTT_PORT
                  name: mqtt-data
                  optional: false
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  key: LIVING_ROOM_AIR_TOPIC
                  name: mqtt-data
                  optional: false
            - name: ALERT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: SLACK_ALERT_ENDPOINT
                  name: slack-service-endpoint
                  optional: false
            - name: CLIMATE_ALERT_WEBHOOK
              valueFrom:
                secretKeyRef:
                  key: CLIMATE_ALERT_WEBHOOK
                  name: climate-alert-secret
                  optional: false           
            - name: DEVICE_FAILURE_CHANNEL
              value: '#iot_device_failures'
            - name: INTERVAL
              value: '15'
            - name: DEVICE_ID
              value: node2
            - name: PLANTOWER_SENSOR_ID
              value: living_room_plantower_air_sensor
            - name: ALERT_THRESHOLD
              value: '25'
            - name: PM2_THRESHOLD
              value: '50'
            - name: PM10_THRESHOLD
              value: '75'
            - name: USB_ADDRESS
              # TODO: create mapping on device
              value: /dev/ttyUSB0 
      imagePullSecrets: 
        - name: docker-creds
      restartPolicy: Always