# Workflow for pulling in weather data from the Open Weather API 
apiVersion: argoproj.io/v1alpha1
kind: cronWorkflow
metadata:
  name: openweather-current-weather
  namespace: etl-pipelines
spec:
  schedule: "*/15 * * * *"
  timezone: "America/Los_Angeles"
  startingDeadlineSeconds: 0
  concurrencyPolicy: replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 5
  suspend: false
  workflowSpec:
    entrypoint: load-weather-data
    imagePullSecrets:
    - name: docker-creds
    templates:
      - name: load-weather-data
        container:
          image: markhamlee/openweather_current
          command: ["python3"]
          args: ["/etl/main.py", "Open Weather. Scheduled on: {{workflow.scheduledTime}}"]
          resources: 
            limits:
              memory: 256Mi
              cpu: 200m
          env:
          - name: INFLUX_KEY
            valueFrom:
              secretKeyRef:
                key: PROD_INFLUX_KEY
                name: influxdb-secret
          - name: OPENWEATHER_KEY
            valueFrom:
              secretKeyRef:
                key: OPEN_WEATHER_SECRET
                name: openweather-secret
          - name: INFLUX_ORG
            valueFrom:
              configMapKeyRef:
                key: PROD_INFLUX_ORG
                name: key-etl-variables
          - name: INFLUX_URL
            valueFrom:
              configMapKeyRef:
                key: PROD_INFLUX_URL
                name: key-etl-variables
          - name: BUCKET
            valueFrom:
              configMapKeyRef:
                key: PROD_DASHBOARD_BUCKET
                name: key-etl-variables
          - name: CITY
            value: seattle
          - name: LAT
            value: '47.6'
          - name: LONG 
            value: '-122.3321'
          - name: WEATHER_MEASUREMENT
            value: weather