apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-quality-office-mkiii
  namespace: iot-devices
spec:
  selector:
    matchLabels: 
      app: air-quality-office-mkiii
  replicas: 1
  template:
    metadata:
      labels:
        app: air-quality-office-mkiii
    spec:
      nodeName: rpinode0
      containers:
        - name: air-quality-office-mkiii
          image: markhamlee/airquality:arm64
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  key: MQTT_USER
                  name: mqtt-creds
                  optional: false
            - name: MQTT_SECRET
              valueFrom:
                secretKeyRef:
                  key: MQTT_SECRET
                  name: mqtt-creds
                  optional: false
            - name: MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: MQTT_BROKER
                  name: mqtt-data
                  optional: false
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  key: MQTT_PORT
                  name: mqtt-data
                  optional: false
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  key: OFFICE_AIR_TOPIC
                  name: mqtt-data
                  optional: false
            - name: ALERT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: SLACK_ALERT_ENDPOINT
                  name: slack-service-endpoint
                  optional: false
            - name: DEVICE_FAILURE_CHANNEL
              value: '#iot_device_failures'
            - name: INTERVAL
              value: '5'
            - name: DEVICE_ID_DATA
              value: rpi_node2_airquality_novapm
            - name: ALERT_THRESHOLD
              value: '25'
            - name: USB_ADDRESS
              # ideally you'd create a name mapping but with the NovaPM this 
              # doesn't seem to work like it does with other USB devices 
              value: /dev/ttyUSB0 
      imagePullSecrets: 
        - name: docker-creds
      restartPolicy: Always