apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-quality-bedroom
  namespace: iot-devices
spec:
  selector:
    matchLabels: 
      app: air-quality
  replicas: 1
  template:
    metadata:
      labels:
        app: air-quality
    spec:
      nodeName: <put name of node the USB device is attached to>
      containers:
        - name: bedroom-air-quality
          image: markhamlee/airquality:arm64
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  key: MQTT_USER
                  name: mqtt-creds
                  optional: false
            - name: MQTT_SECRET
              valueFrom:
                secretKeyRef:
                  key: MQTT_SECRET
                  name: mqtt-creds
                  optional: false
            - name: MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: MQTT_BROKER
                  name: mqtt-data
                  optional: false
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  key: MQTT_PORT
                  name: mqtt-data
                  optional: false
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  key: BEDROOM_AIR_TOPIC
                  name: mqtt-data
                  optional: false
            - name: INTERVAL
              value: '5'
            - name: USB_ADDRESS
              # ideally you'd create a name mapping but with the NovaPM this 
              # doesn't seem to work like it does on other USB devices 
              value: /dev/ttyUSB0 
      imagePullSecrets: 
        - name: docker-creds
      restartPolicy: Always