apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-dht22
  namespace: iot-devices
spec:
  selector:
    matchLabels: 
      app: temperature-dht22
  replicas: 1
  template:
    metadata:
      labels:
        app: temperature-dht22
    spec:
      nodeName: rpinode0 # note: this code will only run on a Raspberry Pi 
      containers:
        - name: temperature-sensor
          image: markhamlee/dht22_monitoring:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  key: MQTT_USER
                  name: mqtt-creds
                  optional: false
            - name: MQTT_SECRET
              valueFrom:
                secretKeyRef:
                  key: MQTT_SECRET
                  name: mqtt-creds
                  optional: false
            - name: MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: MQTT_BROKER
                  name: mqtt-data
                  optional: false
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  key: MQTT_PORT
                  name: mqtt-data
                  optional: false
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  key: temp-topic-livingroom
                  name: mqtt-data
                  optional: false
            - name: DEVICE_FAILURE_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: DEVICE_FAILURE_CHANNEL
                  name: mqtt-data
                  optional: false  
            - name: INTERVAL
              value: '5'
            - name: DEVICE_ID_DATA
              value: rpi_node0_temperature_monitoring
      imagePullSecrets: 
        - name: docker-creds
    restartPolicy: Always