# Deployment Manifest for Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgp30-co2
  namespace: iot-devices
spec:
  selector:
    matchLabels: 
      app: sgp30-co2
  replicas: 1
  template:
    metadata:
      labels:
        app: sgp30-co2
    spec:
      nodeName: rpinode2
      containers:
        - name: sgp30-co2-testing
          image: markhamlee/sgp30_data:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  key: MQTT_USER
                  name: mqtt-creds
                  optional: false
            - name: MQTT_SECRET
              valueFrom:
                secretKeyRef:
                  key: MQTT_SECRET
                  name: mqtt-creds
                  optional: false
            - name: MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: MQTT_BROKER
                  name: mqtt-data
                  optional: false
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  key: MQTT_PORT
                  name: mqtt-data
                  optional: false
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  key: SGP30_TEST_TOPIC
                  name: mqtt-data
                  optional: false      
            - name: DEVICE_FAILURE_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: DEVICE_FAILURE_CHANNEL
                  name: mqtt-data
                  optional: false                     
            - name: INTERVAL
              value: '5'
            - name: DEVICE_ID
              value: rpinode2
            - name: SENSOR_ID
              value: sgp30_test
      imagePullSecrets: 
        - name: docker-creds
      restartPolicy: Always