apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasa-plug-monitoring
  namespace: operations
spec:
  selector:
    matchLabels:
      app: kasa-plug-monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: kasa-plug-monitoring
    spec:
      containers:
        - name: lab-plug-one
          image: <your image repo here>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: PROD_INFLUX_KEY
                  name: influxdb-secret
                  optional: false 
            - name: ORG
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_ORG
                  name: key-ops-variables
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_URL
                  name: key-ops-variables
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: HARDWARE_BUCKET
                  name: key-ops-variables
            - name: SMART_PLUG_TABLE
              valueFrom:
                configMapKeyRef:
                  key: labplug1
                  name: key-ops-variables
            - name: INTERVAL
              value: '5'
            - name: DEVICE_IP
              value: <your IP address here>
        - name: lab-plug-two
          image: <your image repo here>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: PROD_INFLUX_KEY
                  name: influxdb-secret
                  optional: false 
            - name: ORG
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_ORG
                  name: key-ops-variables
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_URL
                  name: key-ops-variables
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: HARDWARE_BUCKET
                  name: key-ops-variables
            - name: SMART_PLUG_TABLE
              valueFrom:
                configMapKeyRef:
                  key: labplug1
                  name: key-ops-variables
            - name: INTERVAL
              value: '5'
            - name: DEVICE_IP
              value: <your IP address here>
        - name: lab-plug-three
          image: <your image repo here>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: PROD_INFLUX_KEY
                  name: influxdb-secret
                  optional: false 
            - name: ORG
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_ORG
                  name: key-ops-variables
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_URL
                  name: key-ops-variables
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: HARDWARE_BUCKET
                  name: key-ops-variables
            - name: SMART_PLUG_TABLE
              valueFrom:
                configMapKeyRef:
                  key: labplug1
                  name: key-ops-variables
            - name: INTERVAL
              value: '5'
            - name: DEVICE_IP
              value: <your IP address here>
        - name: lab-plug-four
          image: <your image repo here>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: PROD_INFLUX_KEY
                  name: influxdb-secret
                  optional: false 
            - name: ORG
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_ORG
                  name: key-ops-variables
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_URL
                  name: key-ops-variables
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: HARDWARE_BUCKET
                  name: key-ops-variables
            - name: SMART_PLUG_TABLE
              valueFrom:
                configMapKeyRef:
                  key: labplug1
                  name: key-ops-variables
            - name: INTERVAL
              value: '5'
            - name: DEVICE_IP
              value: <your IP address here>
      imagePullSecrets: 
        - name: private-docker-repo
      restartPolicy: Always