name: IoT_BME280_TEMP_SENSOR_BUILD

on:
  push:
    branches:
      - "main"
    paths:
      - "IoT/bme280_temp_sensor/*"
      - "IoT/iot_libraries/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./IoT/
          file: ./IoT/bme280_temp_sensor/Dockerfile
          platforms: linux/arm64
          push: true
          tags: markhamlee/bme280_temp:latest