name: finnhub_stocks_container_build_nodejs

on:
  push:
    branches:
      - "main"
    paths:
      - "etl_pipelines_nodejs/finnhub_node/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./etl_pipelines_nodejs/finnhub_nodejs
          file: ./etl_pipelines_nodejs/finnhub_nodejs/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: markhamlee/finnhub_stock_etl:latest