name: Kasa_Smartplug_MQTT_Image_Build

on:
  push:
    branches:
      - "main"
    paths:
    - "IoT/iot_libraries/*"
    - "IoT/kasa_smart_plug_mqtt/*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./IoT/
          file: ./IoT/kasa_smart_plug_mqtt/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: markhamlee/kasa_plugs:latest