name: orangepi3b_monitoring

on:
  push:
    branches:
      - "main"
    paths:
      - "hardware_telemetry/orangepi_3b/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./hardware_telemetry/orangepi_3b/
          file: ./hardware_telemetry/orangepi_3b/Dockerfile
          platforms: linux/arm64
          push: true
          tags: markhamlee/orangepi3b-telemetry:latest